### ISSUE TITLE
support destructuring

### ISSUE THREAD

**Issue by vvo** [yggie/babel-plugin-inline-json-import#6]
Hi, nice plugin! Could be cool to support this:

```js
import {version} from '../../package.json';
console.log(version);
```

Right now it only inline the full file without destructuring support.

**Comment by yggie** [comment]
@vvo I added support for destructuring in the latest version, let me know if it solves your problem and we can close this issue 🙂

**Comment by vvo** [comment]
Works perfectly, bravo!
