### ISSUE TITLE
Doesn't seem to work with `babel-plugin-module-resolver`

### ISSUE THREAD

**Issue by LegNeato** [yggie/babel-plugin-inline-json-import#7]
When using this with `babel-plugin-module-resolver` and having a json import using an alias, an error is thrown because the file cannot be found. This happens both when `inline-json-import` is before or after `babel-plugin-module-resolver` in `.babelrc`.

**Comment by yggie** [comment]
This should be resolved now https://github.com/yggie/babel-plugin-inline-json-import/pull/4 has been merged, feel free to close this issue if this has solved your problem
